Meeting/Home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:meeting_count>/', views.meetings, name='meetings')
]

Meeting/Meeting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls')),
    path("accounts/", include("django.contrib.auth.urls"), name="login"),
]

Meeting/Home/models.py
from django.db import models

# Create your models here.
class Meeting(models.Model):
	meeting_name = models.CharField(max_length=255)
	meeting_count = models.IntegerField(default=1)

Meeting/Home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .models import Meeting

def index(request):
	meeting_list = Meeting.objects.order_by('-meeting_name')
	context = {
		'meeting_list': meeting_list,
	}
	return render(request, 'Home/index.html', context)

def meetings(request, meeting_count):
	return HttpResponse("stuff %s" % meeting_count)

Meeting/Home/templates/Home/index.html
{%extends 'base.html'%}

{%block content%}
    {% if meeting_list%}
        <ul>
        {% for meeting in meeting_list%}
            <li><a href="{% url 'home:meetings' meeting.id %}"> {{ meeting.meeting_name }}</a><li>
        {% endfor %}
        </ul>
    {% else %}
        <p> No Meetings available </p>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
{%endblock%}

Meeting/Home/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}Same Meeting{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SameMeeting</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.8.0/dist/chart.min.js"> </script>
  <script>
    const labels = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
    ];
  
    const data = {
      labels: labels,
      datasets: [{
        label: 'My First dataset',
        backgroundColor: 'rgb(255, 99, 132)',
        borderColor: 'rgb(255, 99, 132)',
        data: [0, 10, 5, 2, 20, 30, 45],
      }]
    };
  
    const config = {
      type: 'line',
      data: data,
      options: {}
    };
  </script>
  
</head>

<body>
  <main>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:index' %}">Same Meeting</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Meetings</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="navbar-brand" href="{% url 'login' %}">Login</a>
          <a class="navbar-brand" href="{% url 'login' %}">Create Account</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container p-5 my-5 border">
      <div class="row">
        <div class="col">
          <div class="container border">
            <canvas id="myChart"></canvas>
          </div>
        </div>
        <div class="col">
          <div class="container border">
            <canvas id="myChart2"></canvas>
          </div>
        </div>
      </div>
      <div class=" d-flex p-5 my-5 border">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </main>
  <script>
    const myChart = new Chart(
      document.getElementById('myChart'),
      config
    );
    const myChart2 = new Chart(
      document.getElementById('myChart2'),
      config
    );
  </script>
  
</body>
</html>